language: python

python:
 - "2.7"

services:
 - docker

before_install:
 - docker pull ubuntu:16.04
 - docker run -it ubuntu bash

install: 
 - sudo apt-get install unixodbc-dev
 - pip install -r requirements.txt

script: python tests/test.py
