language: python
python:
 - "2.7"
install: 
 - sudo su
 - curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
 - curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql.list
 - exit
 - sudo apt-get update
 - sudo apt-get install unixodbc-dev
 - sudo apt-get install msodbcsql mssql-tools
 - pip install -r requirements.txt
script: python tests/test.py
