language: python

python:
 - "2.7"

install: 
 - sudo apt-get install unixodbc-dev
 - pip install -r requirements.txt

script: python tests/test.py

notifications:
  email: false
  slack: movierecommender:wN5gIWudB8YuieaS9yQhmyn6
