language: python

python:
 - "2.7"

install: 
 - sudo apt-get install python-pip
 - wget https://packages.microsoft.com/keys/microsoft.asc
 - wget https://packages.microsoft.com/config/ubuntu/16.04/prod.list
 - sudo apt-key add microsoft.asc
 - sudo mv prod.list /etc/apt/sources.list.d/mssql.list
 - sudo apt-get update
 - sudo apt-get install unixodbc unixodbc-dev
 - sudo apt-get install msodbcsql mssql-tools
 - sudo pip install pyodbc==3.1.1
 - sudo pip install -e .

script: python mrelearner/tests/test.py

notifications:
  email: false
  slack: movierecommender:wN5gIWudB8YuieaS9yQhmyn6
